version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Using Python version:"
      - python --version
      - pip install -r api/requirements.txt
artifacts:
  files:
    - '**/*'
